namespace AffiseAttributionLib.Events.Parameters
{
    public enum PredefinedString
    {
        ADREV_AD_TYPE,
        CITY,
        COUNTRY,
        REGION,
        CLASS,
        CONTENT_ID,
        CONTENT_TYPE,
        CURRENCY,
        CUSTOMER_USER_ID,
        DESCRIPTION,
        DESTINATION_A,
        DESTINATION_B,
        DESTINATION_LIST,
        ORDER_ID,
        PAYMENT_INFO_AVAILABLE,
        PREFERRED_NEIGHBORHOODS,
        PURCHASE_CURRENCY,
        RECEIPT_ID,
        REGISTRATION_METHOD,
        SEARCH_STRING,
        SUBSCRIPTION_ID,
        SUCCESS,
        SUGGESTED_DESTINATIONS,
        SUGGESTED_HOTELS,
        VALIDATED,
        ACHIEVEMENT_ID,
        COUPON_CODE,
        CUSTOMER_SEGMENT,
        DEEP_LINK,
        NEW_VERSION,
        OLD_VERSION,
        PARAM_01,
        PARAM_02,
        PARAM_03,
        PARAM_04,
        PARAM_05,
        PARAM_06,
        PARAM_07,
        PARAM_08,
        PARAM_09,
        PARAM_10,
        REVIEW_TEXT,
        TUTORIAL_ID,
        VIRTUAL_CURRENCY_NAME,
        STATUS,
        BRAND,
        BRICK,
        CATALOGUE_ID,
        CHANNEL_TYPE,
        CUSTOMER_TYPE,
        SEGMENT,
        UTM_CAMPAIGN,
        UTM_MEDIUM,
        UTM_SOURCE,
        VERTICAL,
        VOUCHER_CODE,
        CLICK_ID,
        CAMPAIGN_ID,
        EVENT_NAME,
        PID,
        PRODUCT_ID,
        CONVERSION_ID,
        CONTENT_NAME,
        PRODUCT_NAME,
        SOURCE,
        NETWORK,
        UNIT,
        PLACEMENT,
    }
    
    public static class PredefinedStringExt
    {
        public static string ToValue(this PredefinedString param)
        {
            return $"{PredefinedConstants.PREFIX}{param.Value()}";
        }

        private static string Value(this PredefinedString param)
        {
            return param switch
            {
                PredefinedString.ADREV_AD_TYPE => "adrev_ad_type",
                PredefinedString.CITY => "city",
                PredefinedString.COUNTRY => "country",
                PredefinedString.REGION => "region",
                PredefinedString.CLASS => "class",
                PredefinedString.CONTENT_ID => "content_id",
                PredefinedString.CONTENT_TYPE => "content_type",
                PredefinedString.CURRENCY => "currency",
                PredefinedString.CUSTOMER_USER_ID => "customer_user_id",
                PredefinedString.DESCRIPTION => "description",
                PredefinedString.DESTINATION_A => "destination_a",
                PredefinedString.DESTINATION_B => "destination_b",
                PredefinedString.DESTINATION_LIST => "destination_list",
                PredefinedString.ORDER_ID => "order_id",
                PredefinedString.PAYMENT_INFO_AVAILABLE => "payment_info_available",
                PredefinedString.PREFERRED_NEIGHBORHOODS => "preferred_neighborhoods",
                PredefinedString.PURCHASE_CURRENCY => "purchase_currency",
                PredefinedString.RECEIPT_ID => "receipt_id",
                PredefinedString.REGISTRATION_METHOD => "registration_method",
                PredefinedString.SEARCH_STRING => "search_string",
                PredefinedString.SUBSCRIPTION_ID => "subscription_id",
                PredefinedString.SUCCESS => "success",
                PredefinedString.SUGGESTED_DESTINATIONS => "suggested_destinations",
                PredefinedString.SUGGESTED_HOTELS => "suggested_hotels",
                PredefinedString.VALIDATED => "validated",
                PredefinedString.ACHIEVEMENT_ID => "achievement_id",
                PredefinedString.COUPON_CODE => "coupon_code",
                PredefinedString.CUSTOMER_SEGMENT => "customer_segment",
                PredefinedString.DEEP_LINK => "deep_link",
                PredefinedString.NEW_VERSION => "new_version",
                PredefinedString.OLD_VERSION => "old_version",
                PredefinedString.PARAM_01 => "param_01",
                PredefinedString.PARAM_02 => "param_02",
                PredefinedString.PARAM_03 => "param_03",
                PredefinedString.PARAM_04 => "param_04",
                PredefinedString.PARAM_05 => "param_05",
                PredefinedString.PARAM_06 => "param_06",
                PredefinedString.PARAM_07 => "param_07",
                PredefinedString.PARAM_08 => "param_08",
                PredefinedString.PARAM_09 => "param_09",
                PredefinedString.PARAM_10 => "param_10",
                PredefinedString.REVIEW_TEXT => "review_text",
                PredefinedString.TUTORIAL_ID => "tutorial_id",
                PredefinedString.VIRTUAL_CURRENCY_NAME => "virtual_currency_name",
                PredefinedString.STATUS => "status",
                PredefinedString.BRAND => "brand",
                PredefinedString.BRICK => "brick",
                PredefinedString.CATALOGUE_ID => "catalogue_id",
                PredefinedString.CHANNEL_TYPE => "channel_type",
                PredefinedString.CUSTOMER_TYPE => "customer_type",
                PredefinedString.SEGMENT => "segment",
                PredefinedString.UTM_CAMPAIGN => "utm_campaign",
                PredefinedString.UTM_MEDIUM => "utm_medium",
                PredefinedString.UTM_SOURCE => "utm_source",
                PredefinedString.VERTICAL => "vertical",
                PredefinedString.VOUCHER_CODE => "voucher_code",
                PredefinedString.CLICK_ID => "click_id",
                PredefinedString.CAMPAIGN_ID => "campaign_id",
                PredefinedString.EVENT_NAME => "event_name",
                PredefinedString.PID => "pid",
                PredefinedString.PRODUCT_ID => "product_id",
                PredefinedString.CONVERSION_ID => "conversion_id",
                PredefinedString.CONTENT_NAME => "content_name",
                PredefinedString.PRODUCT_NAME => "product_name",
                PredefinedString.SOURCE => "source",
                PredefinedString.NETWORK => "network",
                PredefinedString.UNIT => "unit",
                PredefinedString.PLACEMENT => "placement",
                _ => null
            };
        }
    }
}