namespace AffiseAttributionLib.Events
{
    internal enum EventName
    {
        ACHIEVE_LEVEL,
        ADD_PAYMENT_INFO,
        ADD_TO_CART,
        ADD_TO_WISHLIST,
        CLICK_ADV,
        COMPLETE_REGISTRATION,
        COMPLETE_STREAM,
        COMPLETE_TRIAL,
        COMPLETE_TUTORIAL,
        CONTACT,
        CONTENT_ITEMS_VIEW,
        CUSTOM_ID_01,
        CUSTOM_ID_02,
        CUSTOM_ID_03,
        CUSTOM_ID_04,
        CUSTOM_ID_05,
        CUSTOM_ID_06,
        CUSTOM_ID_07,
        CUSTOM_ID_08,
        CUSTOM_ID_09,
        CUSTOM_ID_10,
        CUSTOMIZE_PRODUCT,
        DEEP_LINKED,
        DONATE,
        FIND_LOCATION,
        INITIATE_CHECKOUT,
        INITIATE_PURCHASE,
        INITIATE_STREAM,
        INVITE,
        LAST_ATTRIBUTED_TOUCH,
        LEAD,
        LIST_VIEW,
        LOGIN,
        OPENED_FROM_PUSH_NOTIFICATION,
        ORDER,
        ORDER_CANCEL,
        ORDER_RETURN_REQUEST,
        ORDER_RETURN_REQUEST_CANCEL,
        PURCHASE,
        RATE,
        RE_ENGAGE,
        RESERVE,
        SALES,
        SCHEDULE,
        SEARCH,
        SHARE,
        SPEND_CREDITS,
        START_REGISTRATION,
        START_TRIAL,
        START_TUTORIAL,
        SUBMIT_APPLICATION,
        SUBSCRIBE,
        TRAVEL_BOOKING,
        UNLOCK_ACHIEVEMENT,
        UNSUBSCRIBE,
        UPDATE,
        VIEW_ADV,
        VIEW_CART,
        VIEW_CONTENT,
        VIEW_ITEM,
        VIEW_ITEMS,
    }
    
    internal static class EventNameExt
    {
        public static string ToValue(this EventName type)
        {
            return type switch
            {
                EventName.ACHIEVE_LEVEL => "AchieveLevel",
                EventName.ADD_PAYMENT_INFO => "AddPaymentInfo",
                EventName.ADD_TO_CART => "AddToCart",
                EventName.ADD_TO_WISHLIST => "AddToWishlist",
                EventName.CLICK_ADV => "ClickAdv",
                EventName.COMPLETE_REGISTRATION => "CompleteRegistration",
                EventName.COMPLETE_STREAM => "CompleteStream",
                EventName.COMPLETE_TRIAL => "CompleteTrial",
                EventName.COMPLETE_TUTORIAL => "CompleteTutorial",
                EventName.CONTACT => "Contact",
                EventName.CONTENT_ITEMS_VIEW => "ContentItemsView",
                EventName.CUSTOM_ID_01 => "CustomId01",
                EventName.CUSTOM_ID_02 => "CustomId02",
                EventName.CUSTOM_ID_03 => "CustomId03",
                EventName.CUSTOM_ID_04 => "CustomId04",
                EventName.CUSTOM_ID_05 => "CustomId05",
                EventName.CUSTOM_ID_06 => "CustomId06",
                EventName.CUSTOM_ID_07 => "CustomId07",
                EventName.CUSTOM_ID_08 => "CustomId08",
                EventName.CUSTOM_ID_09 => "CustomId09",
                EventName.CUSTOM_ID_10 => "CustomId10",
                EventName.CUSTOMIZE_PRODUCT => "CustomizeProduct",
                EventName.DEEP_LINKED => "DeepLinked",
                EventName.DONATE => "Donate",
                EventName.FIND_LOCATION => "FindLocation",
                EventName.INITIATE_CHECKOUT => "InitiateCheckout",
                EventName.INITIATE_PURCHASE => "InitiatePurchase",
                EventName.INITIATE_STREAM => "InitiateStream",
                EventName.INVITE => "Invite",
                EventName.LAST_ATTRIBUTED_TOUCH => "LastAttributedTouch",
                EventName.LEAD => "Lead",
                EventName.LIST_VIEW => "ListView",
                EventName.LOGIN => "Login",
                EventName.OPENED_FROM_PUSH_NOTIFICATION => "OpenedFromPushNotification",
                EventName.ORDER => "Order",
                EventName.ORDER_CANCEL => "OrderCancel",
                EventName.ORDER_RETURN_REQUEST => "OrderReturnRequest",
                EventName.ORDER_RETURN_REQUEST_CANCEL => "OrderReturnRequestCancel",
                EventName.PURCHASE => "Purchase",
                EventName.RATE => "Rate",
                EventName.RE_ENGAGE => "ReEngage",
                EventName.RESERVE => "Reserve",
                EventName.SALES => "Sales",
                EventName.SCHEDULE => "Schedule",
                EventName.SEARCH => "Search",
                EventName.SHARE => "Share",
                EventName.SPEND_CREDITS => "SpendCredits",
                EventName.START_REGISTRATION => "StartRegistration",
                EventName.START_TRIAL => "StartTrial",
                EventName.START_TUTORIAL => "StartTutorial",
                EventName.SUBMIT_APPLICATION => "SubmitApplication",
                EventName.SUBSCRIBE => "Subscribe",
                EventName.TRAVEL_BOOKING => "TravelBooking",
                EventName.UNLOCK_ACHIEVEMENT => "UnlockAchievement",
                EventName.UNSUBSCRIBE => "Unsubscribe",
                EventName.UPDATE => "Update",
                EventName.VIEW_ADV => "ViewAdv",
                EventName.VIEW_CART => "ViewCart",
                EventName.VIEW_CONTENT => "ViewContent",
                EventName.VIEW_ITEM => "ViewItem",
                EventName.VIEW_ITEMS => "ViewItems",
                _ => null
            };
        }
    }
}