namespace AffiseAttributionLib.Events.Predefined
{
    public enum PredefinedParameters
    {
        ADREV_AD_TYPE,
        CITY,
        COUNTRY,
        REGION,
        CLASS,
        CONTENT,
        CONTENT_ID,
        CONTENT_LIST,
        CONTENT_TYPE,
        CURRENCY,
        CUSTOMER_USER_ID,
        DATE_A,
        DATE_B,
        DEPARTING_ARRIVAL_DATE,
        DEPARTING_DEPARTURE_DATE,
        DESCRIPTION,
        DESTINATION_A,
        DESTINATION_B,
        DESTINATION_LIST,
        HOTEL_SCORE,
        LEVEL,
        MAX_RATING_VALUE,
        NUM_ADULTS,
        NUM_CHILDREN,
        NUM_INFANTS,
        ORDER_ID,
        PAYMENT_INFO_AVAILABLE,
        PREFERRED_NEIGHBORHOODS,
        PREFERRED_NUM_STOPS,
        PREFERRED_PRICE_RANGE,
        PREFERRED_STAR_RATINGS,
        PRICE,
        PURCHASE_CURRENCY,
        QUANTITY,
        RATING_VALUE,
        RECEIPT_ID,
        REGISTRATION_METHOD,
        RETURNING_ARRIVAL_DATE,
        RETURNING_DEPARTURE_DATE,
        REVENUE,
        SCORE,
        SEARCH_STRING,
        SUBSCRIPTION_ID,
        SUCCESS,
        SUGGESTED_DESTINATIONS,
        SUGGESTED_HOTELS,
        TRAVEL_START,
        TRAVEL_END,
        USER_SCORE,
        VALIDATED,
        ACHIEVEMENT_ID,
        COUPON_CODE,
        CUSTOMER_SEGMENT,
        DEEP_LINK,
        EVENT_START,
        EVENT_END,
        LAT,
        LONG,
        NEW_VERSION,
        OLD_VERSION,
        PARAM_01,
        PARAM_02,
        PARAM_03,
        PARAM_04,
        PARAM_05,
        PARAM_06,
        PARAM_07,
        PARAM_08,
        PARAM_09,
        PARAM_10,
        REVIEW_TEXT,
        TUTORIAL_ID,
        VIRTUAL_CURRENCY_NAME
    }

    public static class PredefinedParametersExtensions
    {
        public static string ToValue(this PredefinedParameters param)
        {
            return param switch
            {
                PredefinedParameters.ADREV_AD_TYPE => "affise_p_adrev_ad_type",
                PredefinedParameters.CITY => "affise_p_city",
                PredefinedParameters.COUNTRY => "affise_p_country",
                PredefinedParameters.REGION => "affise_p_region",
                PredefinedParameters.CLASS => "affise_p_class",
                PredefinedParameters.CONTENT => "affise_p_content",
                PredefinedParameters.CONTENT_ID => "affise_p_content_id",
                PredefinedParameters.CONTENT_LIST => "affise_p_content_list",
                PredefinedParameters.CONTENT_TYPE => "affise_p_content_type",
                PredefinedParameters.CURRENCY => "affise_p_currency",
                PredefinedParameters.CUSTOMER_USER_ID => "affise_p_customer_user_id",
                PredefinedParameters.DATE_A => "affise_p_date_a",
                PredefinedParameters.DATE_B => "affise_p_date_b",
                PredefinedParameters.DEPARTING_ARRIVAL_DATE => "affise_p_departing_arrival_date",
                PredefinedParameters.DEPARTING_DEPARTURE_DATE => "affise_p_departing_departure_date",
                PredefinedParameters.DESCRIPTION => "affise_p_description",
                PredefinedParameters.DESTINATION_A => "affise_p_destination_a",
                PredefinedParameters.DESTINATION_B => "affise_p_destination_b",
                PredefinedParameters.DESTINATION_LIST => "affise_p_destination_list",
                PredefinedParameters.HOTEL_SCORE => "affise_p_hotel_score",
                PredefinedParameters.LEVEL => "affise_p_level",
                PredefinedParameters.MAX_RATING_VALUE => "affise_p_max_rating_value",
                PredefinedParameters.NUM_ADULTS => "affise_p_num_adults",
                PredefinedParameters.NUM_CHILDREN => "affise_p_num_children",
                PredefinedParameters.NUM_INFANTS => "affise_p_num_infants",
                PredefinedParameters.ORDER_ID => "affise_p_order_id",
                PredefinedParameters.PAYMENT_INFO_AVAILABLE => "affise_p_payment_info_available",
                PredefinedParameters.PREFERRED_NEIGHBORHOODS => "affise_p_preferred_neighborhoods",
                PredefinedParameters.PREFERRED_NUM_STOPS => "affise_p_preferred_num_stops",
                PredefinedParameters.PREFERRED_PRICE_RANGE => "affise_p_preferred_price_range",
                PredefinedParameters.PREFERRED_STAR_RATINGS => "affise_p_preferred_star_ratings",
                PredefinedParameters.PRICE => "affise_p_price",
                PredefinedParameters.PURCHASE_CURRENCY => "affise_p_purchase_currency",
                PredefinedParameters.QUANTITY => "affise_p_quantity",
                PredefinedParameters.RATING_VALUE => "affise_p_rating_value",
                PredefinedParameters.RECEIPT_ID => "affise_p_receipt_id",
                PredefinedParameters.REGISTRATION_METHOD => "affise_p_registration_method",
                PredefinedParameters.RETURNING_ARRIVAL_DATE => "affise_p_returning_arrival_date",
                PredefinedParameters.RETURNING_DEPARTURE_DATE => "affise_p_returning_departure_date",
                PredefinedParameters.REVENUE => "affise_p_revenue",
                PredefinedParameters.SCORE => "affise_p_score",
                PredefinedParameters.SEARCH_STRING => "affise_p_search_string",
                PredefinedParameters.SUBSCRIPTION_ID => "affise_p_subscription_id",
                PredefinedParameters.SUCCESS => "affise_p_success",
                PredefinedParameters.SUGGESTED_DESTINATIONS => "affise_p_suggested_destinations",
                PredefinedParameters.SUGGESTED_HOTELS => "affise_p_suggested_hotels",
                PredefinedParameters.TRAVEL_START => "affise_p_travel_start",
                PredefinedParameters.TRAVEL_END => "affise_p_travel_end",
                PredefinedParameters.USER_SCORE => "affise_p_user_score",
                PredefinedParameters.VALIDATED => "affise_p_validated",
                PredefinedParameters.ACHIEVEMENT_ID => "affise_p_achievement_id",
                PredefinedParameters.COUPON_CODE => "affise_p_coupon_code",
                PredefinedParameters.CUSTOMER_SEGMENT => "affise_p_customer_segment",
                PredefinedParameters.DEEP_LINK => "affise_p_deep_link",
                PredefinedParameters.EVENT_START => "affise_p_event_start",
                PredefinedParameters.EVENT_END => "affise_p_event_end",
                PredefinedParameters.LAT => "affise_p_lat",
                PredefinedParameters.LONG => "affise_p_long",
                PredefinedParameters.NEW_VERSION => "affise_p_new_version",
                PredefinedParameters.OLD_VERSION => "affise_p_old_version",
                PredefinedParameters.PARAM_01 => "affise_p_param_01",
                PredefinedParameters.PARAM_02 => "affise_p_param_02",
                PredefinedParameters.PARAM_03 => "affise_p_param_03",
                PredefinedParameters.PARAM_04 => "affise_p_param_04",
                PredefinedParameters.PARAM_05 => "affise_p_param_05",
                PredefinedParameters.PARAM_06 => "affise_p_param_06",
                PredefinedParameters.PARAM_07 => "affise_p_param_07",
                PredefinedParameters.PARAM_08 => "affise_p_param_08",
                PredefinedParameters.PARAM_09 => "affise_p_param_09",
                PredefinedParameters.PARAM_10 => "affise_p_param_10",
                PredefinedParameters.REVIEW_TEXT => "affise_p_review_text",
                PredefinedParameters.TUTORIAL_ID => "affise_p_tutorial_id",
                PredefinedParameters.VIRTUAL_CURRENCY_NAME => "affise_p_virtual_currency_name",
                _ => null
            };
        }
    }
}